### ISSUE TITLE
kubernetes on pod

### ISSUE THREAD

**Issue by liangyuanpeng** [liangyuanpeng/liangyuanpeng.github.io#436]
- kind
- k0s 
- k3d
-

**Comment by liangyuanpeng** [comment]
对于 kind 运行在容器内可以参考 kind 运行在 drone 的配置示例参考:

.drone.yaml
```yaml
---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: setup
    image: docker:stable
    pull: always
    depends_on: [ clone ]
    environment:
      CLUSTER_HOST: docker
      CLUSTER_NAME: kind-cluster
      KUBECONFIG: /mnt/config/admin.conf
    commands:
      - ./drone/install.sh
      - ./drone/setup.sh
      - kubectl get nodes
    volumes:
      - name: dockersock
        path: /var/run
      - name: kubeconfig
        path: /mnt/config
    when:
      event:
      - push

  - name: test
    image: alpine:3.14
    pull: always
    depends_on: [ setup ]
    environment:
      KUBECONFIG: /mnt/config/admin.conf
    commands:
      - ./drone/install.sh
      - kubectl get nodes
    volumes:
      - name: kubeconfig
        path: /mnt/config
    when:
      event:
      - push

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
- name: kubeconfig
  temp: {}
```

完整的内容在 https://github.com/kind-ci/examples/tree/master/drone
